name: "Generate Bindings"
description: "Generate .NET bindings"
runs:
  using: "composite"
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
    - name: Generate FFI bindings
      shell: bash
      run: dotnet run --project src/Generator/Generator.csproj
